### ISSUE TITLE
Could not find io.github.dokar3:sheets-m3:v0.5.4

### ISSUE THREAD

**Issue by shreks7** [dokar3/sheets#108]
I am trying to install the library in Jetpack Compose but I keep getting `Could not find io.github.dokar3:sheets-m3:v0.5.4` and I have `mavenCentral` added in my `settings.gradle`.  Any ideas?

**Comment by dokar3** [comment]
Maybe a network problem or something? It's still on Maven Central.

https://search.maven.org/artifact/io.github.dokar3/sheets-m3/0.5.4/aar

**Comment by shreks7** [comment]
Looks like it was the cache, had to invalidate it and now it works. Thank you!
