### ISSUE TITLE
bug with collapsing sheet after reopen application 

### ISSUE THREAD

**Issue by localhostov** [dokar3/sheets#120]
**versions:**
sheets: 0.5.5
android: 14 (but also repeated on 13 & 12) (compileSdk 34 lvl)
kotlin: 1.9.0
compose compiler: 1.5.1

**code for reproduce:**
https://yaso.su/AOgh0Gi2

**video with reproduce (sorry about great quality :) ):**
https://github.com/dokar3/sheets/assets/74156284/0f1f0164-1ba2-4ff9-bb0f-d99f2c3133c0

**Comment by dokar3** [comment]
Thanks for reporting, will look into this later.

**Comment by dokar3** [comment]
Done in #121
The new version will be released soon

**Comment by dokar3** [comment]
The new version is out.
https://github.com/dokar3/sheets/releases/tag/v0.5.6
