### ISSUE TITLE
the sheet doesn't collapse during content resizing

### ISSUE THREAD

**Issue by localhostov** [dokar3/sheets#123]
**versions:**
sheets: 0.5.6
kotlin: 1.9.0
compose compiler: 1.5.1

**code for reproduce:**
https://yaso.su/adyPF0SW

**video with reproduce:**

https://github.com/dokar3/sheets/assets/74156284/0a709fb5-58a1-40ee-8aa6-9c14876b80cc

**Comment by dokar3** [comment]
Thanks for reporting again, will check this when I'm free.
