### ISSUE TITLE
Include the source on maven repo

### ISSUE THREAD

**Issue by re-ovo** [dokar3/sheets#4]
At present, it seems that there is no source code in your maven repository, and users cannot view the comments and definitions of each function.

![image](https://user-images.githubusercontent.com/21152113/172849117-de17a994-223a-4366-ad49-4b7ba2d682f9.png)

Also, there is a mistake in README, the dependency path should be `implementation "io.github.dokar3:sheets:0.1.1"`

Anyway, this is the best sheet library for compose I've seen! 🥰

**Comment by dokar3** [comment]
Thank you for reporting! README.md has been updated and the missing source code issue seems to be related to publishing configurations, Android Studio doesn't seem to recognize both debug-sources.jar and release-sources.jar artifacts now. I'll try to publish the only release variant for upcoming releases, this should solve the problem.

**Comment by dokar3** [comment]
Version 0.1.2 has been released, sources should be available in Android Studio, feel free to upgrade.

**Comment by re-ovo** [comment]
It works, thanks
