### ISSUE TITLE
Bottom sheet no appearing above keyboard

### ISSUE THREAD

**Issue by rezafaraji93** [dokar3/sheets#52]
My bottom sheet content has a search text field to filter items inside bottom sheet. When the keyboard is open my I expect the bottom sheet view to move above the keyboard but just the text field it self remains above the keyboard. I have set the `windowSoftInputMode` in manifest to `adjustResize`. How can I reach to my expected UI?

**Comment by dokar3** [comment]
Hi there, you can try this snippet:

```kotlin
BottomSheet(
    state = state,
    modifier = modifier.imePadding(),
    behaviors = DialogSheetBehaviors(
        dialogWindowSoftInputMode = WindowManager.LayoutParams.SOFT_INPUT_ADJUST_NOTHING,
    )
) {
    // Content
}
```
![Screenshot](https://user-images.githubusercontent.com/68095777/232808653-b4872f67-f918-4447-a343-d58ece1bf41e.png)

**Comment by rezafaraji93** [comment]
Thanks, imePadding did the job!
