### ISSUE TITLE
Unable to use modal bottom sheet or the default bottom sheet along with this

### ISSUE THREAD

**Issue by Eganathan** [dokar3/sheets#55]
modalBottomSheetState.progress, modalBottomSheetState.direction   modalBottomSheetState.current values throws Unresolved reference error

**Comment by dokar3** [comment]
This is peculiar, this library does not interact with other libraries, have you tried to clean/rebuild project?

**Comment by Eganathan** [comment]
Yes, had tried it but does not seem to work.

**Comment by dokar3** [comment]
Not sure why that happens. Can you provide the dependency definitions and Kotlin sample code to reproduce this?

**Comment by dokar3** [comment]
Closed due to no further information provided, it seems we can do nothing on the library side.
