### ISSUE TITLE
Allow to disable the peek feature

### ISSUE THREAD

**Issue by re-ovo** [dokar3/sheets#6]
Allow to disable the peek feature?

**Comment by dokar3** [comment]
Hi there, it's now possible to skip/disable the peek state by setting a large `peekHeight`, e.g. `PeekHeight.fraction(1f)`, `PeekHeight.px(Int.MAX_VALUE)` (see the README for details). But this seems a bit obscure, will add a `skipPeek` parameter directly to the `BottomSheet()` composable.

**Comment by dokar3** [comment]
`skipPeek` has been added to the latest released version 0.1.2, feel free to upgrade.
