### ISSUE TITLE
Sheet wrap content LazyColumn verticalScroll throws Exception

### ISSUE THREAD

**Issue by Czdzdz** [dokar3/sheets#73]
FATAL EXCEPTION: main
java.lang.IllegalStateException: Vertically scrollable component was measured with an infinity maximum height constraints, which is disallowed. One of the common reasons is nesting layouts like LazyColumn and Column(Modifier.verticalScroll()). If you want to add a header before the list of items please add a header as a separate item() before the main items() inside the LazyColumn scope.

**Comment by dokar3** [comment]
LazyColumn should work well within the sheet, any sample code to reproduce the crash?

**Comment by dokar3** [comment]
Closed due to no further information being provided.
