### ISSUE TITLE
Gradle warning after upgrading version to 0.4.6

### ISSUE THREAD

**Issue by rezafaraji93** [dokar3/sheets#74]
After I upgraded to 0.4.6 and my kotlin version to 1.9.0 I get this warning when building release version of my app:

> sheets-0.4.6/jars/classes.jar!/META-INF/sheets_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by dokar3** [comment]
Try updating AGP to 8.1.0, this fixes the sample.
https://github.com/dokar3/sheets/pull/76
