### ISSUE TITLE
Show the bottom sheet dialog in the middle of the screen if not using full width.

### ISSUE THREAD

**Issue by hans-de-clercq** [dokar3/sheets#86]
If I use BottomSheet with `modifier = Modifier.widthIn(max = 600.dp)` the bottom sheet displays at the left side of the screen. 
Is it possible to show the content in the middle of the screen? 

I want to use the bottom sheet on tablets in landscape. I prefer to scrim the whole screen but show the content in the middle in a dialog of max 600.dp width instead of the whole width of the screen.

**Comment by dokar3** [comment]
Currently, there is no such API to change the alignment of the content, but you can wrap your content inside a Box to center the content.
```kotlin
@Composable
fun LimitedWidthBottomSheet(
    maxWidth: Dp = 600.dp,
    state: BottomSheetState,
    modifier: Modifier,
    content: @Composable () -> Unit,
) {
    val scope = rememberCoroutineScope()
    BottomSheet(
        state = state,
        modifier = modifier,
        skipPeeked = true,
        backgroundColor = Color.Transparent,
    ) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .clickable(
                    interactionSource = remember { MutableInteractionSource() },
                    indication = null,
                    onClick = { scope.launch { state.collapse() } },
                ),
            contentAlignment = Alignment.Center,
        ) {
            Box(
                modifier = Modifier
                    .widthIn(max = maxWidth)
                    .clickable(
                        interactionSource = remember { MutableInteractionSource() },
                        indication = null,
                        onClick = { },
                    )
                    .background(
                        color = BottomSheetDefaults.backgroundColor,
                        shape = BottomSheetDefaults.shape,
                    ),
            ) {
                content()
            }
        }
    }
}
```

**Comment by dokar3** [comment]
The next version may add a `contentAlignment` parameter, which will be centered by default, so no changes are required in your case.

**Comment by hans-de-clercq** [comment]
Thank you for the fast reaction. I think adding the contentAlignment parameter will really help. I indeed wrapped the content inside a Box for now, but also needed to use a Column to add a handle myself because otherwise the handle would be outside the content. Using a contentAlignment parameter would make things much more simple, so thank you.

**Comment by dokar3** [comment]
You're welcome, the new version v0.5.1 is out. The new version will not require any changes as the alignment is `CenterHorizontally` by default.

**Comment by hans-de-clercq** [comment]
I just updated to v0.5.1. This is exactly what I wanted. Thanks for the update. Now I can use the same bottom sheet for both phones in portrait and tablets in landscape without any change and without the bottom sheet taking the whole width on a tablet. Perfect!

**Comment by dokar3** [comment]
Glad to hear it works!
