### ISSUE TITLE
Error `java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt`

### ISSUE THREAD

**Issue by tausifcreates** [dokar3/sheets#89]
this error :(

**Comment by dokar3** [comment]
thanks for reporting, this seems to be a Compose dependency conflict issue, have you checked this link?
https://stackoverflow.com/questions/76950205/failed-resolution-of-landroidx-compose-runtime-primitivesnapshotstatekt

**Comment by tausifcreates** [comment]
Hi @dokar3 
Thanks for your help. What compose version does this library use?

**Comment by dokar3** [comment]
That's weird, BOM 2023.10.01 should map to Compose 1.5.3 as this page mentioned: https://developer.android.com/jetpack/compose/bom/bom-mapping.

And PrimitiveSnapshotStateKt should be included in the classes if the dependency Compose Runtime 1.5.3 was applied:

![image](https://github.com/dokar3/sheets/assets/68095777/c62ea72a-b18c-4623-8407-8053c03fb03c)

**Comment by tausifcreates** [comment]
Hi @dokar3, I applied `compose-runtime` and `compose-runtime-saveable`, but still getting same error message. Am I missing any other libs?

**Comment by dokar3** [comment]
It may be conflicted with other libraries/dependencies so the build system picked an older version of runtime, can you force the runtime version to 1.5.4?
```kotlin
implementation("androidx.compose.runtime:runtime") {
    version {
        strictly("1.5.4")
    }
}
```
I got the same error in the sample app after I changed it to 1.4.3.

**Comment by tausifcreates** [comment]
> It may be conflicted with other libraries/dependencies so the build system picked an older version of runtime, can you force the runtime version to 1.5.4?
> 
> ```kotlin
> implementation("androidx.compose.runtime:runtime") {
>     version {
>         strictly("1.5.4")
>     }
> }
> ```
> 
> I got the same error in the sample app after I changed it to 1.4.3.

Thank you, I am trying it out and let you know :)

**Comment by tausifcreates** [comment]
I applied the strict versioning but still get the same error. But mine is not a greenfield project and probably because of that too many libs overlapping with each other. Thanks for your help :) I will update in this thread if I find a solution.

**Comment by dokar3** [comment]
You're welcome, glad to help.
