### ISSUE TITLE
Unwanted Bottomsheet padding on android12 +

### ISSUE THREAD

**Issue by lolafhkahfkjsghd** [dokar3/sheets#90]
![Screenshot_20231030_072428](https://github.com/dokar3/sheets/assets/124862263/9ed35a87-0291-4d9d-9570-79e69378978e)
there is unwanted padding for the bottom padding that occurs only if you are on android 12 and above!

is this a bug or am i doing something wrong?

**Comment by dokar3** [comment]
This seems to be a bug. Can you run the sample app on your device and open the text field bottom sheet to check if you also get the same issue?
If this occurs, can you provide more information, such as the device, the system, and the keyboard app?
If not, can you provide the information above and extra information, such as your composable parameters and the reproduction steps?

Extract it to get the apk:
[sample-debug.zip](https://github.com/dokar3/sheets/files/13200166/sample-debug.zip)

**Comment by lolafhkahfkjsghd** [comment]
sample app works fine on my device.

here is a snippet of my composable

 BottomSheet(
        state = state,
        modifier = modifier.imePadding(),  //might be causing the issue ?
        shape = configs.shape,
        backgroundColor = configs.background,
        skipPeeked = configs.skippedPeek,
        peekHeight = configs.peekHeight,
        dragHandle = configs.handle,
        behaviors = configs.behaviors
    ) {
        content(this)
    }

**Comment by dokar3** [comment]
| modifier = modifier.imePadding(), //might be causing the issue ?

Yes, this is expected behavior, when the whole sheet needs to show above the keyboard, you can combine the `SOFT_INPUT_ADJUST_RESIZE` with `imePadding()`

```kotlin
BottomSheet(
    state = state,
    modifier = modifier.imePadding(),
    behaviors = DialogSheetBehaviors(
        dialogWindowSoftInputMode = WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE
    ),
) {
    TextFieldSheetContent(state = state)
}
```

**Comment by dokar3** [comment]
Will add this to the README

**Comment by dokar3** [comment]
> Yes, this is expected behavior, when the whole sheet needs to show above the keyboard, you can combine the SOFT_INPUT_ADJUST_RESIZE with imePadding()

`showAboveKeyboard` was added to simplify this. 

Check #94

**Comment by lolafhkahfkjsghd** [comment]
Sorry for being late, The issue has been resolved using the suggested method.
