### ISSUE TITLE
Is it possible to customize the top indicator?

### ISSUE THREAD

**Issue by trietbui85** [dokar3/sheets#96]
I don't know if it's possible to customize the top indicator to the arrow UP/DOWN arrow?
For example if the bottom sheet is more than 50% of screen height, then will be DOWN arrow. Otherwise, will be UP arrow.

<img width="700" alt="image" src="https://github.com/dokar3/sheets/assets/340836/9bb67c15-5dca-4d62-bdd6-4d4e9e946756">

**Comment by dokar3** [comment]
This is possible, please check the [dragHandle](https://github.com/dokar3/sheets/blob/5f0fffed85591b0f38f064ddb731a2d565e8df50/sheets/src/main/java/com/dokar/sheets/BottomSheet.material.kt#L46) parameter and [listenable-drag-progress](https://github.com/dokar3/sheets#listenable-drag-progress)
