### ISSUE TITLE
[Feature request] Ability to make navigation bar transparent

### ISSUE THREAD

**Issue by 4nk1r** [dokar3/sheets#99]
I've been using your library for a little while now, and it's definitely better than default compose's implementation. Wanted to make it using native sheets myself, but thankfully I don't need to now :) Anyway, that's not why I'm creating this issue.

In my app I've got system controls fully transparent as I consider it as the only right way. And the thing is that your library isn't setting navigation bar color for dialogs, so it's default system's black as shown below:
<details>
  <summary>Black navigation bar</summary>
  <image src="https://github.com/dokar3/sheets/assets/63253661/3fa92979-9215-41fb-93bc-33d2a94399f4" />
</details>

Android 14 Developer Options allow to force navigation bar to be transparent if another color isn't specified manually, and it looks just like I want it to be:
<details>
  <summary>Transparent navigation bar</summary>
  <image src="https://github.com/dokar3/sheets/assets/63253661/4ac92eaf-f72f-44e3-b1b5-31b9389031e4" />
</details>

The question is, would you please improve your nonetheless great library with this feature? :) AFAIK it's not gonna be hard. Thanks in advance anyway

**Comment by dokar3** [comment]
I'm glad it helped!

You can customize system bar colors through the `behaviors` parameter. 

Will update the readme to point this out and make this feature easier to be known.

https://github.com/dokar3/sheets/blob/78e4cf41e69fff603dacf0b39feb567912d05b1d/sheets-m3/src/main/java/com/dokar/sheets/m3/BottomSheet.material3.kt#L45C1

https://github.com/dokar3/sheets/blob/78e4cf41e69fff603dacf0b39feb567912d05b1d/sheets-m3/src/main/java/com/dokar/sheets/m3/BottomSheetDefaults.material3.kt#L45

**Comment by 4nk1r** [comment]
Oh, didn't notice that... Thanks!

**Comment by dokar3** [comment]
You're welcome! Glad to help here.
